---
title: "Covid Project"
author: "Mitchell Izower"
date: "10/8/2020"
output: html_document
---

```{r} 
library(knitr)    
library(tidyverse) 
library(dplyr)
#load both tables in
covid<-read.csv("./covidclass_without_labels.csv")
covid2<-read.csv("./covidclass_30_percent_labels.csv")
```

```{r} 
#build a list of most common sx of the 30% labeled list
covid2
covid3<-covid2 %>% separate(patientID.labels.chief.complaint., c("ID", "Value", "CC"), sep = "[.|]")
#grouping chief complaints
covid4<-covid3 %>% filter(Value!="") %>% group_by(Value, CC) %>% summarise(Count=n()) %>% ungroup() %>% arrange(desc(Count))
covid4pos<-covid4 %>% filter(Value==1)
covid4neg<-covid4 %>% filter(Value==0)
covid4pos
covid4neg

covid8<-covid3 %>% 
  mutate(
    Value = case_when(
    Value!="0" & Value!="1" ~ "NA",
    Value=="1" ~"1",
    Value=="0" ~"0",
  ))

write.csv(covid8,"./covid8.csv")
```

```{r} 
#Joining tables, determining TP,TN,FP,FN
covid5<-covid3[,c(1,3,2)] %>% rename(Result=Value)
test2<-test %>% separate(patientID.chief.complaint., c("ID", "CC"), sep = "[.|]") %>% rename(Predicted=CovidRisk)
covid5
test2
CovidJoinClass<-left_join(covid5,test2) %>% 
  mutate(
    Class = case_when(
  Result==0 & Predicted==0 ~"TrueNegative",
  Result==1 & Predicted==1 ~"TruePositive",
  Result==0 & Predicted==1 ~"FalsePositive",
  Result==1 & Predicted==0 ~"FalseNegative",
))
FilteredCJC<-CovidJoinClass %>% filter(!is.na(Class)) %>% group_by(Class,CC) %>% summarise(Count=n()) %>% ungroup()

#Recording most common false positives and false negatives
FalseNeg<-FilteredCJC %>% filter(Class=="FalseNegative") %>% arrange(desc(Count))
FalsePos<-FilteredCJC %>% filter(Class=="FalsePositive") %>% arrange(desc(Count))
head(FalseNeg,10)
head(FalsePos,10)

```

```{r}
#sx object contains high risk symptoms
sx<-"fever|chills|cough|shortness of breath|SOB|difficulty breathing|fatigue|muscle aches|body aches|headache|loss of taste|loss of smell|sore throat|congestion|runny nose|nausea|vomiting|diarrhea|trouble breathing|chest pain|confusion|somnolence|blu.|abdominal pain|GI s.|dyspnea|.covid."

#HRcovid dataset contains high risk patients
HRcovid<-covid %>% dplyr::filter(stringr::str_detect(patientID.chief.complaint., regex(sx,ignore_case = TRUE))==TRUE) %>% mutate(CovidRisk=1) 

#LRcovid <- covid %>% dplyr::filter(stringr::str_detect(patientID.chief.complaint., regex(sx,ignore_case = TRUE))==FALSE) %>% mutate(CovidRisk=0) 
  
#Joins and processes high risk data set and low risk data set
test<-covid %>% left_join(HRcovid)
test$CovidRisk<-replace_na(test$CovidRisk,0)
test
test %>% separate(patientID.chief.complaint., c("ID", "CC"), sep = "[.|]")

#Counting
Count_HighRisk_LowRisk<-test %>% group_by(CovidRisk) %>% summarise(Count=n()) %>% ungroup()
Count_HighRisk_LowRisk
Number_Covid_Patients<-Count_HighRisk_LowRisk[2,2]
Number_Covid_Patients
#Remove the comment # to run the next line, which will write/overwrite the output table
#write.csv(test,"./covidclass_with_labels.csv")
#write.csv(Number_Covid_Patients,"./Number of Patients with Covid")
```

```{r}
#Converting terms into regular expression
C1<-read_csv("./CovidDataAllClustersV1.csv") 

Ones<-C1 %>% group_by(CC) %>%  dplyr::filter(stringr::str_detect(CLUSTER, regex("1.",ignore_case = TRUE))==TRUE) %>% summarise(count=n()) %>% arrange(desc(count))
Ones$CC 
comboOne<-paste(c(Ones$CC),collapse='"|CC=="')
#pull out, put in word, remove \
c("Abdominal Pain", "FEVER")
OneAll<-CC=="FEVER"|CC=="ABD PAIN"|CC=="ABDOMINAL PAIN"|CC=="STOMACH ACHE"|CC=="COUGH"|CC=="SHORTNESS OF BREATH"|CC=="SOB - SHORTNESS OF BREATH"|CC=="DYSPNEA"|CC=="CP - CHEST PAIN"|CC=="CHEST PRESSURE"|CC=="CHEST PAIN"|CC=="AMS - ALTERED MENTAL STATUS"|CC=="ALTERED MENTAL STATUS"|CC=="CHEST TIGHTNESS"|CC=="STOMACHACHE"|CC=="DIARRHEA"|CC=="FEVERS"|CC=="ABDO PAIN"|CC=="CONFUSION"|CC=="BODY ACHES"|CC=="SOB"|CC=="COUGH/CONGESTION"|CC=="HEADACHE"|CC=="N/V"|CC=="SHORT OF BREATHE"|CC=="DYSPNEA ON EXERTION"|CC=="NAUSEA AND VOMITING"|CC=="SHORT OF BREATH"|CC=="HA - HEADACHE"|CC=="FLU-LIKE SYMPTOMS"|CC=="NAUSEA"|CC=="CHEST PAIN (NONCARDIAC FEATURES)"|CC=="DOE - DYSPNEA ON EXERTION"|CC=="ILI"|CC=="S/P CHEST PAIN"|CC=="EPIGASTRIC PAIN"|CC=="CHILLS"|CC=="DYPNEA"|CC=="S/P CP"|CC=="C/P"|CC=="RESPIRATORY DISTRESS"|CC=="CHEST PAINS"|CC=="CHEST PAIN (CARDIAC FEATURES)"|CC=="CONFUSED"|CC=="HYPOXEMIA"|CC=="AGITATED"|CC=="I L I"|CC=="ILI - INFLUENZE LIKE ILLNESS"|CC=="N/V/D"|CC=="THROAT PAIN"|CC=="CP"|CC=="FATIGUE"|CC=="INFLUENZA LIKE ILLNESS"|CC=="LOWER ABDOMINAL PAIN"|CC=="HYPOXIA"|CC=="TIREDNESS"|CC=="AGITATION"|CC=="NAUSEA VOMITING DIARRHEA"|CC=="LOW PULSE OX"|CC=="RLQ PAIN"|CC=="RIGHT UPPER QUADRANT PAIN"|CC=="SORE THROAT"|CC=="DOE"|CC=="HALLUCINATIONS"|CC=="RUQ PAIN"|CC=="ASTHMA EXACERBATION"|CC=="HYPOXIC"|CC=="RIGHT LOWER QUADRANT PAIN"|CC=="RUQ ABD PAIN"|CC=="BODY ACHE"|CC=="Epigastric pain"|CC=="DIFFICULTY BREATHING"|CC=="Fatigue"|CC=="RLQ ABD PAIN"|CC=="RLQ ABDOMINAL PAIN"|CC=="DEHYDRATION"|CC=="H/A"|CC=="HEADACHES"|CC=="LLQ ABDOMINAL PAIN"|CC=="Agitation"|CC=="ALTERED M/S"|CC=="BODYACHES"|CC=="BRADYCARDIA"|CC=="CHILL"|CC=="DIAHRREA"|CC=="LEFT LOWER QUADRANT PAIN"|CC=="VOMITING AND/OR NAUSEA"|CC=="ALERTED MENTAL STATUS"|CC=="ALTER MENTAL STATUS"|CC=="AMS"|CC=="CHANGE MS"|CC=="DECREASED PO INTAKE"|CC=="HEMOPTYSIS"|CC=="N&V"|CC=="NVD"|CC=="RIGHT SIDED ABDOMINAL PAIN"|CC=="UPPER ABDOMINAL PAIN"|CC=="ALT MS"|CC=="ALTERED MS"|CC=="CARDIAC ARREST"|CC=="LLQ ABD PAIN"|CC=="MENTAL STATUS CHANGES"|CC=="PNEUMONIA"|CC=="RESP DISTRESS"|CC=="RUQ ABDOMINAL PAIN"|CC=="CHANGE IN MS"|CC=="DIARRHOEA"|CC=="DVT"|CC=="FRANK BLOOD IN SPUTUM"|CC=="NAUSEA VOMITING"|CC=="NAUSEA/VOMITING"|CC=="PE"|CC=="VOMITING"|CC=="Difficulty breathing"|CC=="HA"|CC=="HALLUCINATING"|CC=="Hemoptysis"|CC=="Left sided abdominal pain"|CC=="LEFT SIDED ABDOMINAL PAIN"|CC=="LUQ abd pain"|CC=="MS CHANGE"|CC=="PRODUCTIVE COUGH"|CC=="PULMONARY EMBOLISM"|CC=="RIGHT SIDED ABD PAIN"|CC=="ALT MENTAL STATUS"|CC=="Anorexia"|CC=="ANOREXIA"|CC=="Bradycardia"|CC=="Cardiac arrest"|CC=="CONGESTED NOSE"|CC=="Dehydration"|CC=="HEAD ACHE"|CC=="L CHEST PAIN"|CC=="LOW ABD PAIN"|CC=="LUQ ABDOMINAL PAIN"|CC=="PLEURITIC CHEST PAIN"|CC=="Productive cough"|CC=="R CP - CHEST PAIN"|CC=="R SIDE ABD PAIN"|CC=="SORETHROAT"|CC=="VOMITTING"|CC=="ASTHMA"|CC=="CENTRAL ABDOMINAL PAIN"|CC=="Decreased PO intake"|CC=="DECREASED URINE OUTPUT"|CC=="DIARHHEA"|CC=="ELEVATED WBC"|CC=="INTUBATED"|CC=="L CHEST PRESSURE"|CC=="L CHEST TIGHTNESS"|CC=="LLE DVT"|CC=="LOWER ABD PAIN"|CC=="POSITIVE D-DIMER"|CC=="POSITIVE DVT"|CC=="POSITIVE PE"|CC=="POSITIVE PNA"|CC=="R CHEST PAIN"|CC=="R HA - HEADACHE"|CC=="R SIDED ABD PAIN"|CC=="R WRIST PAIN"|CC=="S/P CARDIAC ARREST"|CC=="STUFFED-UP NOSE"

Zeros<-C1 %>% group_by(CC) %>%  dplyr::filter(stringr::str_detect(CLUSTER, regex("0.",ignore_case = TRUE))==TRUE) %>% summarise(count=n()) %>% arrange(desc(count))
comboZero<-paste(c(Zeros$CC),collapse='"|CC=="') 
#pull out, put in word, remove \

HRcovid<-C1 %>% dplyr::filter(CC=="FEVER"|CC=="ABD PAIN"|CC=="ABDOMINAL PAIN"|CC=="STOMACH ACHE"|CC=="COUGH"|CC=="SHORTNESS OF BREATH"|CC=="SOB - SHORTNESS OF BREATH"|CC=="DYSPNEA"|CC=="CP - CHEST PAIN"|CC=="CHEST PRESSURE"|CC=="CHEST PAIN"|CC=="AMS - ALTERED MENTAL STATUS"|CC=="ALTERED MENTAL STATUS"|CC=="CHEST TIGHTNESS"|CC=="STOMACHACHE"|CC=="DIARRHEA"|CC=="FEVERS"|CC=="ABDO PAIN"|CC=="CONFUSION"|CC=="BODY ACHES"|CC=="SOB"|CC=="COUGH/CONGESTION"|CC=="HEADACHE"|CC=="N/V"|CC=="SHORT OF BREATHE"|CC=="DYSPNEA ON EXERTION"|CC=="NAUSEA AND VOMITING"|CC=="SHORT OF BREATH"|CC=="HA - HEADACHE"|CC=="FLU-LIKE SYMPTOMS"|CC=="NAUSEA"|CC=="CHEST PAIN (NONCARDIAC FEATURES)"|CC=="DOE - DYSPNEA ON EXERTION"|CC=="ILI"|CC=="S/P CHEST PAIN"|CC=="EPIGASTRIC PAIN"|CC=="CHILLS"|CC=="DYPNEA"|CC=="S/P CP"|CC=="C/P"|CC=="RESPIRATORY DISTRESS"|CC=="CHEST PAINS"|CC=="CHEST PAIN (CARDIAC FEATURES)"|CC=="CONFUSED"|CC=="HYPOXEMIA"|CC=="AGITATED"|CC=="I L I"|CC=="ILI - INFLUENZE LIKE ILLNESS"|CC=="N/V/D"|CC=="THROAT PAIN"|CC=="CP"|CC=="FATIGUE"|CC=="INFLUENZA LIKE ILLNESS"|CC=="LOWER ABDOMINAL PAIN"|CC=="HYPOXIA"|CC=="TIREDNESS"|CC=="AGITATION"|CC=="NAUSEA VOMITING DIARRHEA"|CC=="LOW PULSE OX"|CC=="RLQ PAIN"|CC=="RIGHT UPPER QUADRANT PAIN"|CC=="SORE THROAT"|CC=="DOE"|CC=="HALLUCINATIONS"|CC=="RUQ PAIN"|CC=="ASTHMA EXACERBATION"|CC=="HYPOXIC"|CC=="RIGHT LOWER QUADRANT PAIN"|CC=="RUQ ABD PAIN"|CC=="BODY ACHE"|CC=="Epigastric pain"|CC=="DIFFICULTY BREATHING"|CC=="Fatigue"|CC=="RLQ ABD PAIN"|CC=="RLQ ABDOMINAL PAIN"|CC=="DEHYDRATION"|CC=="H/A"|CC=="HEADACHES"|CC=="LLQ ABDOMINAL PAIN"|CC=="Agitation"|CC=="ALTERED M/S"|CC=="BODYACHES"|CC=="BRADYCARDIA"|CC=="CHILL"|CC=="DIAHRREA"|CC=="LEFT LOWER QUADRANT PAIN"|CC=="VOMITING AND/OR NAUSEA"|CC=="ALERTED MENTAL STATUS"|CC=="ALTER MENTAL STATUS"|CC=="AMS"|CC=="CHANGE MS"|CC=="DECREASED PO INTAKE"|CC=="HEMOPTYSIS"|CC=="N&V"|CC=="NVD"|CC=="RIGHT SIDED ABDOMINAL PAIN"|CC=="UPPER ABDOMINAL PAIN"|CC=="ALT MS"|CC=="ALTERED MS"|CC=="CARDIAC ARREST"|CC=="LLQ ABD PAIN"|CC=="MENTAL STATUS CHANGES"|CC=="PNEUMONIA"|CC=="RESP DISTRESS"|CC=="RUQ ABDOMINAL PAIN"|CC=="CHANGE IN MS"|CC=="DIARRHOEA"|CC=="DVT"|CC=="FRANK BLOOD IN SPUTUM"|CC=="NAUSEA VOMITING"|CC=="NAUSEA/VOMITING"|CC=="PE"|CC=="VOMITING"|CC=="Difficulty breathing"|CC=="HA"|CC=="HALLUCINATING"|CC=="Hemoptysis"|CC=="Left sided abdominal pain"|CC=="LEFT SIDED ABDOMINAL PAIN"|CC=="LUQ abd pain"|CC=="MS CHANGE"|CC=="PRODUCTIVE COUGH"|CC=="PULMONARY EMBOLISM"|CC=="RIGHT SIDED ABD PAIN"|CC=="ALT MENTAL STATUS"|CC=="Anorexia"|CC=="ANOREXIA"|CC=="Bradycardia"|CC=="Cardiac arrest"|CC=="CONGESTED NOSE"|CC=="Dehydration"|CC=="HEAD ACHE"|CC=="L CHEST PAIN"|CC=="LOW ABD PAIN"|CC=="LUQ ABDOMINAL PAIN"|CC=="PLEURITIC CHEST PAIN"|CC=="Productive cough"|CC=="R CP - CHEST PAIN"|CC=="R SIDE ABD PAIN"|CC=="SORETHROAT"|CC=="VOMITTING"|CC=="ASTHMA"|CC=="CENTRAL ABDOMINAL PAIN"|CC=="Decreased PO intake"|CC=="DECREASED URINE OUTPUT"|CC=="DIARHHEA"|CC=="ELEVATED WBC"|CC=="INTUBATED"|CC=="L CHEST PRESSURE"|CC=="L CHEST TIGHTNESS"|CC=="LLE DVT"|CC=="LOWER ABD PAIN"|CC=="POSITIVE D-DIMER"|CC=="POSITIVE DVT"|CC=="POSITIVE PE"|CC=="POSITIVE PNA"|CC=="R CHEST PAIN"|CC=="R HA - HEADACHE"|CC=="R SIDED ABD PAIN"|CC=="S/P CARDIAC ARREST"|CC=="STUFFED-UP NOSE") %>% mutate(CovidRisk=1)

C2<-left_join(C1,HRcovid)
C2$CovidRisk<-replace_na(C2$CovidRisk,0)  
C2a<-C2 %>% arrange(patientID)%>% select(-"CLUSTER")
covidrearrange<-covid3[,c(1,3,2)] %>% rename("patientID"="ID") 
combinedcovid<-covidrearrange %>% mutate(Predicted=C2a$CovidRisk) %>% rename(Result=Value)

CClabel<-combinedcovid %>% 
  mutate(
    Class = case_when(
  Result==0 & Predicted==0 ~"TrueNegative",
  Result==1 & Predicted==1 ~"TruePositive",
  Result==0 & Predicted==1 ~"FalsePositive",
  Result==1 & Predicted==0 ~"FalseNegative",
))

#write.csv(CClabel,"./CClabel.csv")

FilteredCClabel<-CClabel %>% filter(!is.na(Class)) %>% group_by(Class,CC) %>% summarise(Count=n()) %>% ungroup()

#Recording most common false positives and false negatives
FalseNeg1<-FilteredCClabel %>% filter(Class=="FalseNegative") %>% arrange(desc(Count))
FalsePos1<-FilteredCClabel %>% filter(Class=="FalsePositive") %>% arrange(desc(Count))
head(FalseNeg1,10)
head(FalsePos1,10)

```
 